---
# Area
- name: area/github
  color: "72ccf3"
  description: >-
    Changes made in the github directory
- name:  area/argocd-app
  color: "72ccf3"
  description: >-
    Changes made appear to be for ArgoCD based application
- name: area/helm
  color: "72ccf3"
  description: >-
    Changes made appear to be for Helm Chart
- name: area/custom-alerts
  color: "72ccf3"
  description: >-
    Changes made in the custom-alerts directory
- name: area/README-update
  color: "72ccf3"
  description: >-
    Changes made to a README.md file
- name: area/kustomization
  color: "72ccf3"
  description: >-
    Changes made appear to be for Kustomization file
- name: area/image-update
  color: "72ccf3"
  description: >-
    Changes made include images

# Uncategorized
- name: bug
  color: "d73a4a"
  description: >-
    Something isn't working
- name: do-not-merge
  color: "d73a4a"
- name: documentation
  color: "0075ca"
  description: >-
    Improvements or additions to documentation
- name: duplicate
  color: "cfd3d7"
  description: >-
    This issue or pull request already exists
- name: enhancement
  color: "a2eeef"
  description: >-
    New feature or request
- name: help wanted
  color: "008672"
  description: >-
    Extra attention is needed
- name: broken-links
  color: "7B55D7"
- name: question
  color: "d876e3"
  description: >-
    Further information is requested
- name: community
  color: "0e8a16"
