---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: external-snapshotter
kind: Kustomization

bases:
  - ./base/client/config/
  - ./base/deploy/csi-snapshotter/

images:
  # https://github.com/kubernetes-csi/external-provisioner/releases
  - name: registry.k8s.io/sig-storage/csi-provisioner
    newTag: v3.3.0
  # https://github.com/kubernetes-csi/external-snapshotter/releases
  - name: registry.k8s.io/sig-storage/csi-snapshotter
    newTag: v6.1.0
  # https://github.com/kubernetes-csi/csi-driver-host-path/releases
  - name: registry.k8s.io/sig-storage/hostpathplugin
    newTag: v1.9.0

patches:
  # Set revisionHistoryLimit on StatefulSet
  - patch: |-
      - op: add
        path: /spec/revisionHistoryLimit
        value: 3
    target:
      kind: StatefulSet
      name: csi-snapshotter
