---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - service-monitor.yaml

configMapGenerator:
  - name: mosquitto-broker-dashboard-11542
    files: [ mosquitto-dashboard.json ]

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "true"
