# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
# https://www.zigbee2mqtt.io/guide/configuration/

---
# yaml-language-server: $schema=https://json.schemastore.org/helmfile

controller:
  type: statefulset

image:
  repository: ghcr.io/koenkk/zigbee2mqtt
  tag: 1.30.4

env:
  TZ: America/New_York
  ZIGBEE2MQTT_DATA: /config
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: "false"
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
  ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
  ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
  ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info # debug
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
  ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: 60
  ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: 2000
  ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
  ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
  ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
  ZIGBEE2MQTT_CONFIG_FRONTEND_PORT: &port 80
  ZIGBEE2MQTT_CONFIG_FRONTEND_URL: https://zigbee2mqtt.example.com
  ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
  ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
  ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: 60
  ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
  ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://mosquitto-mqtt.mosquitto
  ZIGBEE2MQTT_CONFIG_MQTT_BASE_TOPIC: zigbee2mqtt
  ZIGBEE2MQTT_CONFIG_MQTT_VERSION: 5
  ZIGBEE2MQTT_CONFIG_MQTT_USER:
    valueFrom:
      secretKeyRef:
        name: zigbee-mqtt-auth-secret
        key: mqtt-user
  ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: zigbee-mqtt-auth-secret
        key: mqtt-pass
  ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
  ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: 115200
  ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED: "false"
  ZIGBEE2MQTT_CONFIG_SERIAL_PORT: tcp://192.168.1.100:6638

envFrom:
  - secretRef:
      name: zigbee2mqtt-secret

service:
  main:
    ports:
      http:
        port: *port

ingress:
  main:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.middlewares: "traefik-traefik-basic-auth@kubernetescrd"
    hosts:
      - host: &host "zigbee2mqtt.example.com"
        paths:
          - path: /
            pathType: Prefix

podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  fsGroupChangePolicy: OnRootMismatch

volumeClaimTemplates:
  - name: config
    mountPath: /config
    accessMode: ReadWriteOnce
    size: 100Mi
    storageClass: ceph-block

# -- Affinity constraint rules to place the Pod with MQTT Broker
affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - mosquitto
        topologyKey: "kubernetes.io/hostname"

resources:
  requests:
    cpu: 65m
    memory: 150Mi
  limits:
    memory: 500Mi